plasma_cash/child_chain/block.py
plasma_cash/child_chain/child_chain.py
plasma_cash/child_chain/exceptions.py
plasma_cash/child_chain/server.py
plasma_cash/client/child_chain_service.py
plasma_cash/client/client.py
plasma_cash/utils/merkle/sparse_merkle_tree.py
plasma_cash/utils/utils.py

Apply Sparse Merkle Tree (SMT) to block to generate merkle root.
Add `submit_block()` and `get_current_block()` function.

Create sparse merkle tree

---

.flake8
.gitignore
plasma_cash/child_chain/block.py
plasma_cash/child_chain/child_chain.py
plasma_cash/child_chain/server.py
plasma_cash/child_chain/transaction.py
plasma_cash/client/child_chain_service.py
plasma_cash/client/client.py
plasma_cash/client/exceptions.py
plasma_cash/root_chain/deployer.py
plasma_cash/utils/merkle/sparse_merkle_tree.py
plasma_cash/utils/utils.py
requirements.txt
unit_tests/utils/merkle/test_sparse_merkle_tree.py

- add test for merkle tree
- run flake8 and fix code style (with length 99), see `.flake8` config
- isort files to sort import
pytest unit_tests
- pytest unit_tests
- flake8 plasma_cash/
- flake8 unit_tests/
- isort

add test for merkle tree

---

plasma_cash/child_chain/block.py
plasma_cash/child_chain/child_chain.py
plasma_cash/child_chain/server.py
plasma_cash/utils/merkle/sparse_merkle_tree.py
unit_tests/child_chain/test_child_chain.py

as title.
use `mockito` to stub dependencies.

unit test for child chain

---

unit_tests/child_chain/test_child_chain.py
unit_tests/child_chain/test_transaction.py
unit_tests/unstub_mixin.py

unit test for transaction.py

---

plasma_cash/utils/merkle/predicate.py
plasma_cash/utils/merkle/sparse_merkle_tree.py
unit_tests/utils/merkle/test_predicate.py
unit_tests/utils/merkle/test_sparse_merkle_tree.py

Create `create_merkle_proof()` and `is_valid_proof()` methods in SMT.
fix #35

Add merkle proof related

---

plasma_cash/child_chain/server.py
plasma_cash/dependency_config.py
unit_tests/child_chain/test_server.py

- fix create multiple child_chain instance issue. (would register multiple event listening)
- use `DependencyContainer` to initiate and provide instance.

use dependency container

---

plasma_cash/child_chain/__init__.py
unit_tests/child_chain/test_server.py

add unit_test flag in create_app

fix circular dependency import issue

---

plasma_cash/child_chain/child_chain.py
plasma_cash/dependency_config.py
plasma_cash/utils/db/db_interface.py
plasma_cash/utils/db/exceptions.py
plasma_cash/utils/db/memory_db.py
unit_tests/child_chain/test_child_chain.py
unit_tests/utils/db/test_memory_db.py

fix #45
- create db interface
- implement memory db as for faster development & test.

db interface & MemoryDb impl

---

plasma_cash/client/client.py
plasma_cash/root_chain/contracts/RootChain/RootChain.sol

Originally, user didn't actually deposit ether to the contract.
Fix this bug.

Deposit ether

---

README.md
integration_tests/features/basic_flow.feature
integration_tests/features/environment.py
integration_tests/features/steps/basic_flow.py
plasma_cash/client/child_chain_client.py
plasma_cash/client/client.py
plasma_cash/dependency_config.py
plasma_cash/root_chain/contracts/RootChain/RootChain.sol
requirements.txt

- BDD style integ test
- would automatically spin up `ganache` & `child chain server`
- run basic flow, which a user deposit and transfer to another user, and then the another user start exit (see `basic_flow.feature`)
- to run test: `behave integration_tests/features/`

integration test for basic flow

---

.gitignore
README.md
plasma_cash/child_chain/child_chain.py
plasma_cash/config.py
plasma_cash/dependency_config.py
plasma_cash/utils/db/db_interface.py
plasma_cash/utils/db/leveldb.py
plasma_cash/utils/db/memory_db.py
requirements.txt
unit_tests/child_chain/test_child_chain.py
unit_tests/client/test_client.py
unit_tests/utils/db/test_leveldb.py
unit_tests/utils/db/test_memory_db.py

fix #46 
- leveled DAO implementing
- add `db_config` for controlling which db DAO to use

leveldb DAO implement

---

.travis.yml

Implement issue #31, Run Travis CI

Run Travis CI

---

plasma_cash/root_chain/contracts/Libraries/merkle.sol

[Typo] spedific to specific on root/Merkle.sol

---

README.md
integration_tests/features/environment.py

- avoid Ganache keep printing noice while integration test
- fix README challenge case explanation

Some minor fixes

---

integration_tests/features/basic_flow.feature
integration_tests/features/challenge_double_spending_flow.feature
integration_tests/features/challenge_history_flow.feature
integration_tests/features/challenge_spent_coin_flow.feature
integration_tests/features/steps/basic_flow.py
integration_tests/features/steps/challenge_double_spending_flow.py
integration_tests/features/steps/challenge_history_flow.py
integration_tests/features/steps/challenge_spent_coin_flow.py
integration_tests/features/utils.py
plasma_cash/child_chain/block.py
plasma_cash/root_chain/contracts/RootChain/RootChain.sol
plasma_cash/utils/merkle/sparse_merkle_tree.py
unit_tests/child_chain/test_block.py
unit_tests/root_chain/test_root_chain.py

Also, fix a minor bug that the depth of merkle tree should be 257.

Add root chain tests

---

.gitignore
.travis.yml
README.md

Would show coverage in README
See: https://github.com/codecov/example-python

add coverage test

---

plasma_cash/child_chain/__init__.py
plasma_cash/child_chain/child_chain.py
plasma_cash/child_chain/event.py
plasma_cash/child_chain/server.py
plasma_cash/child_chain/websocket.py
unit_tests/child_chain/test_event.py

1. ChildChain can now notify clients through WebSocket
2. The sample notification is `new block creation`, all the clients joined
to the operator will be notified.
The sample code for client is
```
from plasma_cash.dependency_config import container
c = container.get_child_chain_client()
c.on('block', print)
c.emit('join', 'alice')
```
and the latest block number will be printed out when someone calls
`submit_block`.

Event notification system for operator

---

plasma_cash/root_chain/deployer.py

For further information: https://github.com/ethereum/web3.py/issues/740

Fix root chain contract address

---

plasma_cash/child_chain/server.py
plasma_cash/client/child_chain_client.py
unit_tests/client/test_child_chain_client.py

Fix test_emit sometimes doesn't work as expect.

Dump dict to json in explicit order to pass tests

---

.isort.cfg
README.md
integration_tests/features/environment.py
integration_tests/features/steps/challenge_double_spending_flow.py
integration_tests/features/steps/challenge_history_flow.py
plasma_cash/child_chain/__init__.py
plasma_cash/child_chain/block.py
plasma_cash/child_chain/child_chain.py
plasma_cash/child_chain/child_chain_client.py
plasma_cash/child_chain/exceptions.py
plasma_cash/child_chain/server.py
plasma_cash/client/exceptions.py
plasma_cash/dependency_config.py
plasma_cash/operator_cron_job/__main__.py
plasma_cash/operator_cron_job/job_handler.py
plasma_cash/operator_cron_job/jobs/apply_deposit_job.py
plasma_cash/operator_cron_job/jobs/job_interface.py
plasma_cash/operator_cron_job/jobs/submit_block_job.py
unit_tests/child_chain/test_child_chain.py
unit_tests/child_chain/test_child_chain_client.py
unit_tests/child_chain/test_event.py
unit_tests/child_chain/test_server.py
unit_tests/client/test_client.py
unit_tests/operator_cron_job/jobs/test_apply_deposit_job.py
unit_tests/operator_cron_job/jobs/test_submit_block_job.py
unit_tests/operator_cron_job/test_job_handler.py
unit_tests/operator_cron_job/test_main.py

- fix #84, #82
- Design for the cron job flow is `Cron Job` -- call operator api ---> `Child chain server`
- Folder structure changes: move `child_chain_client` to be under `child_chain` since it is now re-used between `client` and `operator_cron_job`
- Separate Child chain server api to two sets: `api` & `operator`. (See the Blueprint change)
This commit does NOT include integration tests code change.

Add Operator Cron jobs: SubmitBlock, ApplyDesposit

---

integration_tests/features/exit_deposit_flow.feature
integration_tests/features/steps/basic_flow.py
integration_tests/features/steps/challenge_double_spending_flow.py
integration_tests/features/steps/challenge_history_flow.py
integration_tests/features/steps/challenge_spent_coin_flow.py
integration_tests/features/steps/exit_deposit_flow.py
plasma_cash/child_chain/child_chain.py
plasma_cash/client/client.py
plasma_cash/root_chain/contracts/RootChain/RootChain.sol
unit_tests/child_chain/test_child_chain.py
unit_tests/client/test_client.py
unit_tests/root_chain/test_root_chain.py

Fix deposit flaw
